name: product_flow-backend

services:
  products_db_dev:
    container_name: product-db-dev
    image: postgres:18.0
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT_DEV:-7600}:5432"
    volumes:
      - postgres_product_dev:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - eshop-network
    profiles: ["dev"]

  products_db_prod:
    container_name: product-db-prod
    image: postgres:18.0
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT_PROD:-7601}:5432"
    volumes:
      - postgres_product_prod:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - eshop-network
    profiles: ["prod"]

  minio_dev:
    container_name: minio-dev
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server /data/minio --console-address ":9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio-secret-key}
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_BUCKET_NAME_PRODUCT: ${MINIO_BUCKET_NAME_PRODUCT:-product-chunks}
      MINIO_BUCKET_NAME_LOKI: ${MINIO_BUCKET_NAME_LOKI:-loki-chunks}
      MINIO_BUCKET_NAME_TEMPO: ${MINIO_BUCKET_NAME_TEMPO:-tempo-traces}
    ports:
      - "${MINIO_API_PORT_DEV:-9002}:9000" # API
      - "${MINIO_CONSOLE_PORT_DEV:-9003}:9001" # Web-консоль
    volumes:
      - minio_data_dev:/data/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - eshop-network
    profiles: ["dev"]

  minio_prod:
    container_name: minio-prod
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server /data/minio --console-address ":9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio-secret-key}
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_BUCKET_NAME_PRODUCT: ${MINIO_BUCKET_NAME_PRODUCT:-product-chunks}
      MINIO_BUCKET_NAME_LOKI: ${MINIO_BUCKET_NAME_LOKI:-loki-chunks}
      MINIO_BUCKET_NAME_TEMPO: ${MINIO_BUCKET_NAME_TEMPO:-tempo-traces}
    ports:
      - "${MINIO_API_PORT_PROD:-9004}:9000" # API
      - "${MINIO_CONSOLE_PORT_PROD:-9001}:9001" # Web-консоль
    volumes:
      - minio_data_prod:/data/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - eshop-network
    profiles: ["prod"]

  products-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-products-prod
    env_file:
      - .env
    environment:
      APP_ENV: prod
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@products_db_prod:5432/${POSTGRES_DB}
      MINIO_ENDPOINT: http://minio_prod:9000
      MINIO_PUBLIC_ENDPOINT: http://localhost:${MINIO_API_PORT_PROD:-9004}
    ports:
      - "9000:8000"
    depends_on:
      products_db_prod:
        condition: service_healthy
      minio_prod:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - eshop-network
    profiles: ["prod"]

volumes:
  postgres_product_dev:
  postgres_product_prod:
  minio_data_dev:
  minio_data_prod:

networks:
  eshop-network:
    driver: bridge
