# Generated by `vulture --make-whitelist .` — false positives to keep vulture quiet.
# `cls` is required by the @field_validator classmethod signature (pydantic v2)
# even though the validators below don't reference it in their body.
cls = None
__all__ = ["cls"]
