services:
  identity-api:
    environment:
      APP_ENV: dev
    ports:
      - "9013:8000"

  identity-worker:
    environment:
      APP_ENV: dev

  identity-bootstrap:
    environment:
      SKIP_SEED: "true"

  catalog-bootstrap:
    environment:
      SKIP_SEED: "true"

  catalog-api:
    environment:
      APP_ENV: dev
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_ENDPOINT: http://localhost:9002
    ports:
      - "9014:8000"

  opensearch:
    ports:
      - "9200:9200"

  redis:
    ports:
      - "6379:6379"

  support-api:
    environment:
      APP_ENV: dev
    ports:
      - "9015:8000"

  minio:
    ports:
      - "9002:9000"
      - "9003:9001"

  identity-db:
    ports:
      - "5441:5432"

  catalog-db:
    ports:
      - "5442:5432"

  support-db:
    ports:
      - "5443:5432"

  gateway:
    ports:
      - "8080:80"
