services:
  identity-api:
    environment:
      APP_ENV: dev
    ports:
      - "9010:8000"

  catalog-api:
    environment:
      APP_ENV: dev
    ports:
      - "9011:8000"

  support-api:
    environment:
      APP_ENV: dev
    ports:
      - "9012:8000"
