services:
  identity-api:
    environment:
      APP_ENV: prod
    restart: unless-stopped

  identity-worker:
    environment:
      APP_ENV: prod
    restart: unless-stopped

  catalog-api:
    environment:
      APP_ENV: prod
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_ENDPOINT: http://localhost:9004
    restart: unless-stopped

  support-api:
    environment:
      APP_ENV: prod
    restart: unless-stopped

  minio:
    ports:
      - "9004:9000"
      - "9001:9001"

  gateway:
    ports:
      - "80:80"
    restart: unless-stopped
