# Generated by `vulture --make-whitelist .` — false positives to keep vulture quiet.
# configured_identity_key (kernel-platform tests) — pytest fixture parameter
# requested only for its setup side effect (генерирует ключ и подменяет путь
# в identity core settings) — тесты никогда не используют само значение.
configured_identity_key = None
__all__ = ["configured_identity_key"]
