apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":\s*"(\w+)"'
          datasourceUid: tempo
          url: '$${__value.raw}'
          urlDisplayLabel: "Открыть трейс в Tempo"

  - name: OpenSearch (catalog)
    uid: opensearch-catalog
    type: elasticsearch
    access: proxy
    url: http://opensearch:9200
    database: catalog-products
    editable: false
    jsonData:
      flavor: opensearch
      version: "3.1.0"
      timeField: created_at
      logMessageField: name
      logLevelField: category
