# Generated by `vulture --make-whitelist .` — false positives to keep vulture quiet.
# TokenVerifier.verify_token/FakeTokenVerifier.verify_token — Protocol/test-double
# method signature, param unused by design in the stub body.
token = None
__all__ = ["token"]
