apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-service
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 8000
